@startuml

!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/v2.3.0/C4_Context.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

title Bank - Context

Enterprise_Boundary(company, "Bank") {
    System(messagingWebPage, "Communication WebPage")
    SystemDb(redis, "Redis Database")
    SystemDb(postgres, "PostgreSQL Database")
    Container_Boundary(gke, "GKE"){
        System(apiGateway, "API Gateway (Kong)")
        System(authApi, "Authentication API")
        System(userApi, "User API")
        System(generateFilesAPI, "Generate Files API")
        System(profileApi, "Profile API")
        System(messagingApi, "Communication API")
        System(partnerBrokerApi, "Partner Broker API")
    }
    SystemQueue(queue, "Pub/Sub System")
    System(CloudFunctions, "Cloud Functions System")
    System(logstash, "Logstash")
    System(kibana, "Kibana")
    System(elasticsearch, "Elasticsearch")
    System(grafana, "Grafana")
    SystemDb(cloudStorage, "cloudStorage")
}

Person(user, "User")
System_Ext(bankPartner, "Bank Partner")
System_Ext(plataformPartner, "Plataform Partner")
System_Ext(extCommunication, "Communication Send System")

Rel(user, company, "Uses")
BiRel(bankPartner, company, "Uses")
BiRel(plataformPartner, company, "Uses")
Rel(company, extCommunication, "Sends messages to")


@enduml